### ISSUE TITLE
Routes - Missing Type declaration

### ISSUE THREAD

**Issue by riffy** [sajjadalis/f7-vue-typescript#1]
Hi,

Thank you very much for the template 😍. I don't know if we are allowed to make PRs so I just open this issue.

Current Situation:
The `routes` variable in `src/routes/router.ts` is missing the correct type declarations.

```
var routes = [
```

Proposed solution:
Add the type declarations from `import { Router } from "framework7/types";`

```
var routes: Router.RouteParameters[] = [
```

If it's okay I would make a PR with this change.
Again thanks for the template!

I'm currently getting to know how the router etc. works, so any improvement there would be helpful (e.g. how to navigate the router outside of `<f7-link>` tags with the correct type-safety).

**Comment by sajjadalis** [comment]
Hi,

You're welcome and thank you for using this and for the contribution. 

Yes. Please test it on your end and submit a PR. Any improvements are welcome.

**Comment by sajjadalis** [comment]
@riffy I just pushed an update which added import type for routes and fixed some other type issues with capacitor-app.ts. Thanks for the contribution. If you have any other issues, let me know or make a PR.
